### ISSUE TITLE
Not able to revert back to old setting.json setting for terminal

### ISSUE THREAD

**Issue by DhirajKoli** [piyush-bhatt/vscode-base16-terminal#1]
I used this extension to try changing the theme for my terminal. But when tried to disable this extension and revert back to my old setting.json configured terminal look, it was not able to do so. I stuck on the theme from this extension.

**Comment by erikwatson** [comment]
@DhirajKoli the extension changes your theme settings directly in the projects .vscode folder in the settings.json file. 
Look for workbench.colorCustomizations and remove everything in there.

Maybe it could remove those when uninstalling, but how would it know if you tweaked them manually or not?

**Comment by piyush-bhatt** [comment]
Apologies for the super late reply, @DhirajKoli. As mentioned by @erikwatson, removing the terminal customisations from `workbench.colorCustomizations` in `settings.json` can get you reverted to the default terminal theme. I have, however, added the command `Remove Terminal Theme` to the new version of the extension but it has to be executed with the risk of losing any changes that may have been made to the terminal theme colors by someone other than this extension, as there's no way of knowing the same.
