### ISSUE TITLE
Terminal theme change cannot go back to default

### ISSUE THREAD

**Issue by afiqket** [piyush-bhatt/vscode-base16-terminal#2]
Just installed and tried it out, then I wanted to go back to default settings and colours. I couldn't. I've installed other terminal theme extensions to try and override it, but the theme still stays. I've disabled and uninstalled and it still doesn't change the colour. I've changed the VS Code's colour theme, and yet the colour of the terminal still won't change. I've gone into settings.json, deleted all statements with "terminal" in them. Still nothing. How do I change it back to default and stop it from overriding everything?

**Comment by afiqket** [comment]
Fixed. I have no understanding of this code and got this through trial and error.

Basically, go to the extension's directory, in the folder `dist`, open up `extension.js`

or in windows:
`%USERPROFILE%\.vscode\extensions\piyush-bhatt.base16-terminal-1.0.0\dist`

Now just copy paste this code right before `3024`
`none:{"terminal.background":false,"terminal.foreground":false,"terminalCursor.background":false,"terminalCursor.foreground":false,"terminal.ansiBlack":false,"terminal.ansiBlue":false,"terminal.ansiBrightBlack":false,"terminal.ansiBrightBlue":false,"terminal.ansiBrightCyan":false,"terminal.ansiBrightGreen":false,"terminal.ansiBrightMagenta":false,"terminal.ansiBrightRed":false,"terminal.ansiBrightWhite":false,"terminal.ansiBrightYellow":false,"terminal.ansiCyan":false,"terminal.ansiGreen":false,"terminal.ansiMagenta":false,"terminal.ansiRed":false,"terminal.ansiWhite":false,"terminal.ansiYellow":false},`

Save, close vscode and reopen it, open the command palette and select Set Terminal Theme as usual, then select None. It should remove all the effects.

**Comment by piyush-bhatt** [comment]
Hi @skpcboy, removing the terminal customisations from `workbench.colorCustomizations` in `settings.json` can get you reverted to the default terminal theme. I have, however, added the command `Remove Terminal Theme` to the extension in the new version but it has to be executed with the risk of losing any changes that may have been made to the terminal theme colors by someone other than this extension, as there's no way of knowing the same.
